'use server'

import { createSupabaseServerClient } from '@/lib/supabase/server'
import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY!)

export async function subscribeToNewsletter(formData: FormData) {
    const email = formData.get('email')?.toString()
    if (!email) return { error: 'Please enter a valid email address.' }

    const supabase = await createSupabaseServerClient()

    // 🔎 Prüfen, ob Mail schon existiert
    const { data: existing } = await supabase
        .from('newsletter_subscribers')
        .select('email')
        .eq('email', email)
        .maybeSingle()

    if (existing) return { error: 'You are already subscribed!' }

    // 💾 In Supabase speichern
    const { error } = await supabase.from('newsletter_subscribers').insert({ email })
    if (error) {
        console.error(error)
        return { error: 'Something went wrong. Please try again later.' }
    }

    // ✅ Willkommens-Mail an den Abonnenten
    try {
        await resend.emails.send({
            from: 'NeoSpend Newsletter <newsletter@neospend.de>',
            to: email,
            replyTo: 'neospend@gmail.com',
            subject: 'Welcome to NeoSpend 💸',
            html: `
      <html>
      <body style="margin:0;padding:0;background-color:#f8f8fb;font-family:Inter,Arial,sans-serif;color:#222;">
        <div style="max-width:520px;margin:40px auto;background:white;border-radius:12px;overflow:hidden;box-shadow:0 8px 24px rgba(0,0,0,0.06);">
          <div style="background:linear-gradient(135deg,#6C63FF,#A491FF);color:white;text-align:center;padding:28px 20px;">
            <h1 style="margin:0;font-size:22px;">Welcome to NeoSpend 💸</h1>
            <p style="margin:8px 0 0;font-size:14px;opacity:0.9;">Smarter finance starts here</p>
          </div>

          <div style="padding:30px 26px;">
            <p style="font-size:16px;margin-top:0;">Hey there 👋</p>
            <p style="font-size:15px;margin-bottom:18px;">
              Thanks for subscribing! You'll soon receive updates about smarter finance tools, design insights, and product improvements by Nils Plützer.
            </p>
            <div style="text-align:center;margin:28px 0;">
              <a href="https://neospend.de" 
                 style="background:#7546E8;color:white;padding:10px 22px;border-radius:8px;text-decoration:none;display:inline-block;font-weight:500;">
                 Visit NeoSpend
              </a>
            </div>
            <p style="font-size:13px;color:#777;text-align:center;margin-top:30px;">
              © ${new Date().getFullYear()} NeoSpend. All rights reserved.
            </p>
          </div>
        </div>
      </body>
      </html>
      `,
        })
    } catch (err) {
        console.error('❌ Failed to send welcome email:', err)
    }

    // ✅ Benachrichtigung an dich selbst
    try {
        await resend.emails.send({
            from: 'NeoSpend Notifications <no-reply@neospend.de>',
            to: process.env.CONTACT_RECEIVER || 'neospend@gmail.com',
            subject: '🆕 New Newsletter Subscriber',
            html: `
      <html>
      <body style="font-family:Inter,Arial,sans-serif;color:#1a1a1a;">
        <div style="max-width:480px;margin:0 auto;padding:20px;">
          <h2 style="color:#7546E8;margin-bottom:10px;">New Subscriber 🚀</h2>
          <p style="margin:0 0 8px;">A new user just joined your NeoSpend newsletter:</p>
          <p style="background:#f6f5ff;border-left:4px solid #7546E8;padding:12px 16px;border-radius:6px;">
            <strong>${email}</strong>
          </p>
          <p style="margin-top:24px;font-size:13px;color:#666;">
            This message was automatically generated by your website.<br>
            <a href="${process.env.SITE_URL || 'https://neospend.de'}" style="color:#7546E8;text-decoration:none;">
              Visit dashboard
            </a>
          </p>
        </div>
      </body>
      </html>
      `,
        })
    } catch (err) {
        console.error('❌ Failed to send admin notification:', err)
    }

    return { success: 'You have been successfully subscribed!' }
}