export const siteConfig = {
    title: 'NeoSpend',
    description:
        "Hello, I'm Nils. I am a Junior Software Developer from Germany. I enjoy building sites and apps. My focus is React (Next.js) with PloneCMS.",
    keywords: [
        'Nils Plützer',
        'Front-end developer',
        'Back-end developer',
        'Junior developer',
        'Full-stack developer',
        'Germany',
        'React',
        'Next.js',
        'Web development',
        'Front-end',
        'Back-end',
        'Full-stack',
        'UI/UX',
        'Responsive design',
        'JavaScript',
        'HTML',
        'CSS',
        'Portfolio',
        'Projects',
        'Website',
        'Web applications',
        'Developer',
        'Code',
        'Programming',
        'Tech enthusiast',
    ],
};